services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: myapp_api
    ports:
      - "3000:3000"

  nginx:
    image: nginx:stable
    container_name: myapp_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - api

  certbot:
    image: certbot/certbot
    container_name: myapp_certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    entrypoint: tail -f /dev/null
    restart: "no"

volumes:
  certbot-etc:
  certbot-var:

